#ifndef PROTOTIPOS_H_INCLUDED
#define PROTOTIPOS_H_INCLUDED



///PROTOTIPOS MENUS

void MENU_VENTAS(void);///CONTIENE EL MENU DE LAS VENTAS
void MENU_ARTICULOS(void);///CONTIENE EL MENU ARTICULOS
void MENU_COMPRAS(void);///CONTIENE EL MENU COMPRAS
void MENU_CLIENTES(void);///CONTIENE EL MENU CLIENTE
void MENU_EMPLEADOS(void);///CONTIENE EL MENU EMPLEADO
void MENU_REPORTES(void);///CONTIENE EL MENU DE LOS REPORTES
void MENU_CONFIGURACIONES(void);///CONTIENE EL MENU DE LAS CONFIGURACIONES

///PROTOTIPOS VENTAS

void NuevaVenta(void);///GENERAMOS UNA VENTA
void mostrarcompras(VENTADETALLADA *,int);///MOSTRAMOS LAS COMPRAS DE UN CLIENTE
float guardarVentas(VENTADETALLADA *,int);///GRABAMOS LAS VENTAS DETALLADAS EN ARCHIVO VENTASDETALLADAS.DAT
void MostraVentas(void);///MOSTRAMOS LAS COMPRAR POR VENTAS ARCHIVO VENTAS.DAT Y VENATASDETALLADAS.DAT
void EliminarCompraVenta(VENTADETALLADA*,float *);///ELIMINAMOS UNA COMPRA
void EliminarVentaCompleta(void);///ELIMINAMOS UN VENTA DEL ARCHIVO VENTAS.DAT
void CompraCorrecta(VENTADETALLADA & ,ARTICULOS &);///VERIFICAOS QUE LA CANTIDAD REQUERIDA NO SEA MAYOR A LA CANTIDAD EN STOCK

///PROTOTIPOS ARTICULOS

void NuevoArticulo(void);///CREAMOS UN NUEVO ARTICULOS
void ModificarArticulo(void);
void ListarArticulos(void);///LISTAMOS LOS ARTICULOS DEL ARCHIVO ARTICULOS
void EliminarArticulo(void);///ELIMINAMOS UN REG DEL ARCHIVO ARTICULO.DAT

void CambiarPrecio(void);///MODIFICAMOS EL PRECIO DE UN ARTICULO
void CambiarPrecioTodos(void);///MODIFICAMOS EL PRECIO DE TODOS LOS ARTICULOS
int  BuscarCodigoArticulo(int);///DEVUELVE LA POSICION DE UN REG EN EL ARCHIVO

int VerificarStock(int);///VERIFICAMOS EL STOCK  0=stock 0   -1=stock <stock min  1=stock >stock max
void FamiliasArticulo(char *,int);///BUSCAMOS FAMILIAS
     ///LISTA

void Lista_A_Secuencial(void);///LISTAMOS LOS ARTICULOS EN EL ORDEN QUE SE CREARON
void Lista_A_Familia(void);///LISTAMOS TODOD LOS ART CON MISMA FAMILIA
void Articulos_Escasos(void);///MOSTRAMOS LOS ARTICULOS CON STOCK POR DEBAJO DEL STOCK MINIMO
void Articulos_En_Excesos(void);///MOSTRAMOS LIS ARTICULOS CON STOCK POR ARRIBA DEL STOCK MAXIMO
///PROTOTIPOS COMPRAS

void NuevoPedido(void);///CREAMOS UN REG PEDIDO Y LO GUARDAMOS
void ListarPedidos(void);///LISTAMOS TODOS LOS REG DEL ARCHIVO COMPRAS.DAT
void ModificarPedido(void);///MODIFICAMOS UN REG COMPRA DEL ARCHIVO COMPRA.DAT
void EliminarPedido(void);///ELIMINAR UN REG DEL ARCHIVO COMPRAS.DAT
void PedidosComprados(void);///

///PROTOTIPO CLINETES

void NuevoCliente(void);///AGREGAMOS UN REG EN EL ARCHIVO CLIENTES.DAT
void ModificarCliente(void);///MODIFICAMOS UN REG DEL ARCHIVO CLIENTES.DAT
void ListarCliente(void);///LISTAMOS LOS REG DEL ARCHIVO CLIENTES.DAT
void EliminarCliente(void);///ELIMINAMOS UN REG DEL ARCHIVO CLINETES.DAT
int BuscarCliente(int);///DEVOLVEMOS LA POSICION DE UN REG CLIENTE
int BuscarClineteBaja(int);///DEVOLEMOS LA POSICION DE UN REG DADO DE BAJA

///PROTOTIPO EMPLEADO

void NuevoEmpleado(void);///AGREAGAMOS UN REG EN EL ARCHIVO EMPLEADO.DAT
void ModificarEmpleado(void);///MODIFICAMOS UN REG DEL ARCHIVO EMPLEADO.DAT
void ListarEmpleado(void);///LISTAMOS LOS REG DEL ARCHIVO EMPLEADO.DAT
void EliminarEmpleado(void);///ELIMINAMOS UN REG DEL ARCHIVO EMPLEADO.DAT
int BuscarEmpleado(int);///DEVOLVEMOS LA POSICION DE UN REG EMPLEADO
int BuscarEmpleadoBaja(int);///DEVOLVEMOS LA POSICION DE UN REG DADO DE BAJA



///PROTOTIPO REPORTES

void ImporteAhora(void);///MOSTRAS EL IMPORTE DE LA FECHA

void CantidadImporteXvendedor(void);///MOSTRAMOS LA CANRIDAD DE VENTAS Y IMPORTE QUE REALIZO UN VEN EN UN FECHA

void CantidadImporte(int ,int *,float *,int ,int ,int);///OBTENEMOS LA CANTIDAD Y EL IMPORTE DE VENDEDOR

void ArticuloMasVendido(void);///MOSTRAMOS EL ART MAS VENDIDO

int buscarMayor(int *,int );///DEVOLOVEMOS LA POSICION DEL MAYOR

void ImporteFecha(void);///MOSTRAMOS EL IMPORTE DE UNA FECHA DETERMINADA

void ClienteConMasCompras(void);///MOSTRAMOS EL CLIENTE CON MAS COMPRAS

int CantidadVD(int);///DEVOLVEMOS LA CANTIDAD DE VENTAS DETALLADES DE UN VENTA CABECERA

///PROTOTIPO CONFIGURACIONES

void CopiaSeguridad(void);///REALIZAMOS UNA COPIA DE LOS ARCHIVOS

void BKPventasDetalles(void);///COPIA VD
void BKPventas(void);///COPIAS VENTAS
void BKParticulos(void);///COPIA ARTICULOS
void BKPcompras(void);///COPIA COMPRAS
void BKPclientes(void);///COPIA CLIENTE
void BKPempleados(void);///COPIA EMPLEADO

void RestablerCopia(void);///SE RESTAURA LOS REG GUARDADOS

void RTventasDetalles(void);///RESTAURAMOS LOS REG VENTAS DETALL.
void RTventas(void);///RESTAURAMOS LOS REG VENTAS
void RTarticulos(void);///RESTAURAMOS LOS REG ARTICULOS
void RTcompras(void);///RESTAURAMOS LOS REG COMPRAS
void RTclientes(void);///RESTAURAMOS LOS REG CLIENTE
void RTempleados(void);///RESTAURAMOS LOS REG EMPLEADO

void AltaClinete();///DAMOS DE ALTA UN CLINETE ELIMINADO

void AltaEmpleado();///DAMOS DE ALTA UN EMPLEADO ELIMINADO


///PROTOTIPO DE VALIDACION

int ValidarE(void);///VALIDAMOS EL DNI DEL EMPLEADO

int ValidarC(void);///VALIDAMOS EL DNI CLIENTE

int ValidarA(int,int);///VALIDADOS EL CODIGO DEL ARTICULO HASTA QUE SE INGRESE UN EXISTENTE


///PROTOTIPO FUNCINES NECESARIAS

int cantidadReg(const char *,int );///NOS DEVUELVE LA CANTIDAD DE REG QUE HAY EN EL ARCHIVO VENTAS.DAT
                                   ///FUNCIONES RECIBE DOS PARAMETROS EL NOMBRE DEL ARCHIVO A ABRIR Y EL
                                   ///TRAMAÑO DE CADA REGUITROS DE ESTE (TAMAÑO OBJ)
void LimpiarRegArchivo(const char *);///LIMPIA EL ARCHIVO QUE SE LE MANDE

///CONTRASENIA


int VerificarContrasenia(void);

void CambiarContrasenia(void);

///PROTOTIPO ERROR

void Error(float,int,int);
void Vcero(int *,int);///PONER EN CERO VENTOR


#endif // PROTOTIPOS_H_INCLUDED
